### ISSUE TITLE
Counters for things over time

### ISSUE THREAD

**Issue by dyc3** [StevensSEC/pokemonbattlelib#135]
**Is your feature request related to a problem? Please describe.**

We don't have a way to increment/decrement counters for specific things. For example, the sleep status conditions stays in effect for 2 to 5 turns, and we don't have a way to track how many turns have passed.

**Describe the solution you'd like**

The battle could keep track of counters. The counters would be a map of some hashable type to integers.

Possible API example
```go
counterId := getStatusCounterId(partyId, slotId, StatusSleep)
b.counters[counterId] = 5
if b.counters[counterId] == 0 {
    // ...
}
```

**Describe alternatives you've considered**

We could put the counters in the pokemon struct, but that would make that struct bigger, and less reusable for other tasks.

**Additional context**

**Comment by adapap** [comment]
I think a map approach is fine, but I do think it should be attached to the relevant type. For example, counters on the battle should be linked to the battle (if something like this exists?), and I believe that attaching it to Pokemon rather than the battle makes it easier to only change relevant ones. This way we can avoid an active Pokemon check if it is attached to the battle.

**Comment by adapap** [comment]
#143 will not include weather stopping naturally, as this is required for that to work.
